config/routes.rb
Rails.application.routes.draw do

  # root page 
  root 'welcome#index'

  # resources 
  resources :games, except: [:index]
  resources :users, except: [:edit, :update]

  # sign up routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # log in routes 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # friendship route -- added method
  post '/users/:id/friendship' => 'users#friendship'

  # bandaid route -- added method
  post '/games/:id/bandaid' => 'games#bandaid'

end

app/models/user.rb
class User < ApplicationRecord
# set bcrypt
  has_secure_password
  
# set associations
  has_many :games
  has_many :friendships
  has_many :friends, through: :friendships

# set validations 
  validates_presence_of :name
  validates_presence_of :username
  validates_presence_of :password

# method to increment win by one
# called from application_controller by games_controller
# calls increment games_played method below
  def increment_win
    self.games_won += 1 
    increment_games_played
  end 

# method to increment loss by one
# called from application_controller by games_controller
# calls increment games_played method below
  def increment_loss
    self.games_lost += 1
    increment_games_played
  end

# method to increment games played by one
# called in the increment methods above
  def increment_games_played
    self.games_played += 1
  end 

# method to decrement bandaid count by one
# called in the bandaid action in games controller 
  def decrement_bandaid
    self.bandaids -= 1
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :friendship, :destroy]

# get method for all users
# get a list of users who have played at least one game
# order them in descending order of win rate
  def index
    @users = User.where('games_played > ?', 0).order('games_won / games_played DESC')
  end 

# get method for new user form (sign up form)
  def new
    @current_user = User.new
    respond_to do |format|
      format.js { render 'new' }
      format.html 
    end 
  end 

# post method for creating a new user (click sign up button)
  def create
    @current_user = User.new(user_params)
    if @current_user.save
      session[:user_id] = @current_user.id
      redirect_to user_path(@current_user)
    else
      @errors = @current_user.errors
      render 'new'
    end
  end 

# get method for user profile page 
# stores all the user's games in an instance variable 
  def show
    @games = @current_user.games
  end 

# post method for friendship creation
# called when someone clicks on "Add Friend"
# redirects to current_user profile page 
  def friendship
    @friendship = Friendship.create!(user_id: @current_user.id, friend_id: @user.id)
    redirect_to user_path(@current_user)
  end 

# delete method for ending friendships
# called when someone clicks on "Unfriend"
# redirects to current_user profile page 
  def destroy
    @friendship = Friendship.where(user_id: @current_user.id, friend_id: @user.id)
    @friendship[0].destroy
    redirect_to user_path(@current_user)
  end 

private 

# this method ensures that the user is passing in valid params(strings)
# protection against passing in viruses through forms 
  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end

# this method is called in the before_action for any action that has a user object
# it's duty is to store the object in an instance variable
# I included it here to make my code DRY
  def set_user 
    @current_user = current_user
    @user = User.find(params[:id])
  end 

end

app/views/users/_connection.html.erb
<div class="connection ui segment">

  <div class="connection-header">
    <h2 class="ui headers">Connections</h2>
  </div>

  <% @user.friends.each do |friend| %>
    <li><%= link_to friend.username, user_path(friend) %></li>
  <% end %>

</div>

app/views/users/_form.html.erb
<div class="signup user-form">
  <center><h2 class="ui headers">Sign Up</h2></center>
  <%= form_for @current_user, html: { class: "ui form" } do |f| %>

    <% if @errors %>
      <ul>
      <% @errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    <% end %>

    <div class= "field">
      <label>Name</label> 
      <%= f.text_field :name, placeholder: "Name" %>
    </div>

    <div class= "field">
      <label>Username</label> 
      <%= f.text_field :username, placeholder: "Username" %>
    </div>

    <div class= "field">
      <label>Password</label> 
      <%= f.password_field :password, placeholder: "Password" %>
    </div>

    <div class= "field">
      <label>Confirm Password</label> 
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
    </div>
      <center><%= f.submit "Submit", class: "ui red button" %></center>
  <% end %>

  <center>Already a member? <%= link_to "Log In", login_path, remote: true %></center>
</div>

app/views/users/_playbutton.html.erb
<%= button_to 'Play A Game', root_path, method: :get, class: "ui red button" %>

app/views/users/_profilename.html.erb
<h1 class="ui headers"><%= @user.name.capitalize %>'s Profile! </h1>

<div class="friend-unfriend-button">
  <table>
    <tr>
      <td> <%= button_to "#{current_user.name}'s Profile", user_path(current_user), class: "ui red button", method: :get %></td>
      <td>
        <%if current_user.friends.include?(@user) %>
          <%= button_to "Unfriend", { action: "destroy", id: @user.id }, method: :delete, data: { confirm: "Are you sure?" }, class: "ui red button" %>
        <% else %>
          <% if current_user.id != @user.id %>
            <%= button_to "Add Friend", { action: "friendship" }, class: "ui red button" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/users/_score.html.erb
<div class="score ui segment">

  <div class="scoreboard-header">
    <h2 class="ui headers">Scoreboard</h2>
  </div>

  <div class="won">
    <li><b>Games won:</b> <%= @user.games_won.to_i %></li>
  </div>

  <div class="lost">
    <li><b>Games lost:</b> <%= @user.games_lost %></li>
  </div>

  <div class="played">
    <li><b>Games played:</b> <%= @user.games_played %></li>
  </div>

  <br><%= button_to 'See how you compare', users_path, method: :get, class: "ui red button" %>

</div>

app/views/users/_track.html.erb
<div class="tracker">
  <h2 class="ui headers">Check out our top players: </h2>
  <table class="ui striped table">
    <thead class="center aligned">
      <tr>
        <th>Rank</th>
        <th>Username</th>
        <th>Win Rate</th>
        <th>Games Won</th>
        <th>Games Played</th>
      </tr>
    </thead>

    <tbody class="center aligned">
    <% count = 1 %>
    <% @users.each do |user| %>
      <tr>
        <td><%= count %></td>
        <td><%= link_to user.username, user_path(user) %></td>
        <td><%= (user.games_won.to_f / user.games_played * 100).to_i %>%</td>
        <td><%= user.games_won.to_i %></td>
        <td><%= user.games_played %></td>
        <% count +=1 %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/_welcome.html.erb
<h1 class="ui headers">Welcome, <%= @current_user.name %>! ( <%= link_to 'log out', logout_path %> )</h1>

app/views/users/index.html.erb
<div class="ui container segments">
  <center><h1 class="ui headers">Leader Board</h1></center><br>
  <center><h3>Do you have what it takes to be the best?</h3></center><br>
  <center><%= render 'playbutton' %></center><br><br>
  <center><%= render 'track' %></center>
</div>

app/views/users/new.html.erb
<div class="ui container segment">
  <%= render 'form' %>
</div>

app/views/users/new.js.erb
$(".login").hide(); 
$(".form-here").html("<%= j render 'form' %> ")

app/views/users/show.html.erb
<div class="ui container segments">
  <div class="ui segment">
    <% if current_user == @user %>
      <center><%= render 'welcome' %></center><br>
      <center><%= render 'playbutton' %></center>
    <% else %>
      <center><%= render 'profilename' %>
    <% end %>
  </div>
  <div class="ui horizontal container segments">
    <div class="ui segment">
      <%= render 'score' %>
    </div>
    <div class="ui segment">
      <%= render 'connection' %>
    </div>
  </div>
</div>