config/routes.rb
Rails.application.routes.draw do

  # root page 
  root 'welcome#index'

  # resources 
  resources :games, except: [:index]
  resources :users, except: [:edit, :update]

  # sign up routes
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # log in routes 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # friendship route -- added method
  post '/users/:id/friendship' => 'users#friendship'

  # bandaid route -- added method
  post '/games/:id/bandaid' => 'games#bandaid'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end 

end

app/views/welcome/_difficulty.html.erb
<div class="difficulty-level">
  <center>
  <h2 class="ui header">Click a difficulty level to begin a game</h2>

  <table>
    <tr>
      <td><%= button_to 'Easy', games_path, class: "difficulty ui red button", params: { difficulty: rand(1..3).to_s } %></td>
      <td><%= button_to 'Medium', games_path, class: "difficulty ui red button", params: { difficulty: rand(4..7).to_s } %></td>
      <td><%= button_to 'Hard', games_path, class: "difficulty ui red button", params: { difficulty: rand(8..10).to_s } %></td>
      <td><%= button_to 'Surprise Me', games_path, class: "difficulty ui red button", params: { difficulty: rand(1..10).to_s }%></td>
    </tr>
  </table>
  </center>
</div>

app/views/welcome/_navigation.erb
<div class="nav-buttons">
  <center>
  <h2 class="ui headers">Explore</h2>
    <div class="profile-page">
      <%= button_to "#{current_user.name}'s Profile", user_path(current_user), class: "ui red button", method: :get %>
    </div><br>

    <div class="leader-board">
      <%= button_to "Leader Board", users_path, class: "ui red button", method: :get %>
    </div><br>

    <div class="logout">
      <%= button_to 'Log Out', logout_path, class: "ui red button", method: :get %>
    </div>
  </center>
</div>

app/views/welcome/_rule.html.erb
<div class="rules>">
  <center><h1 class="ui header">Rules of the Game</h1></center><br>
  <li class="rule">Your opponent, the computer, will select a word for you to guess based off your chosen difficulty level</li>
  <li class="rule">The word will be displayed to you, but hidden. You will then guess a letter</li>
  <li class="rule">If that letter is in the word, it will be placed everywhere the letter would appear in the actual word</li>
  <li class="rule">If that letter is not in the word, a body part will be added to be hung</li>
  <li class="rule">You have six chances to guess a letter that's not in the word before the game is over</li>
  <li class="rule">If you select all the letters in the word, you win</li>
  <li class="rule">Members of this site are given three "band-aids" which allow you an extra guess</li>
  <li class="rule">Members also have access to see the Hangman leaderboard and add friends</li>
</div>

app/views/welcome/index.html.erb
<div class="front-page ui container center raised segments">
  <div class="ui horizontal container segments">
    <div class="ui container segment" >
      <%= render 'rule' %><br>
      <%= render 'difficulty' %><br>
    </div>
    <div class="ui container segment">
      <% if current_user %>
        <%= render 'navigation' %>
      <% else %>
        <%= render 'sessions/form' %>
        <div class="form-here">
        </div><br>
      <% end %>
    </div>
  </div>
</div>